linters-settings:
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  gocyclo:
    min-complexity: 14
  dupl:
    threshold: 300
  lll:
    line-length: 200

linters:
  enable-all: false
  enable:
    - deadcode
    - dupl
    - gocyclo
    - goconst
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - structcheck
    - staticcheck
    - typecheck
    - unconvert
    - varcheck

run:
  concurrency: 4
  deadline: 5m