---
#slack_token: <bot_token>>
#slack_channel: <channel_name>
#prometheus_url: <prom_url>
#s3_bucket: <s3_bucket_name>
#s3_region: eu-west-1

http_port: 8081
metric_resolution: 100

header_template: |
  *{{ .Labels.alertname }}*
  *Status:* {{if eq .Status "firing" }}:fire: Firing{{else}}:white_check_mark: Resolved{{ end }}
  {{ if .Labels.severity }}*Severity:*  `{{ .Labels.severity }}`{{ end }}
  *Alert:* {{ if .Annotations.title }}{{ .Annotations.title }}{{ end }}{{ if .Annotations.summary }}{{ .Annotations.summary }}{{ end }}
  
message_template: |
  *Actions:* :chart_with_upwards_trend: *<{{ .GeneratorURL }}|Graph>*
  {{- if .Annotations.alertman_url }} :bell: *<{{ .Annotations.alertman_url }}|View Alert>*{{ end }}
  {{- if .Annotations.silence_url }} :no_bell: *<{{ .Annotations.silence_url }}|Silence Alert>*{{ end }}
  {{- if .Annotations.runbook }} :notebook: *<{{ .Annotations.runbook }}|Runbook>*{{ end }}
  {{ if .Annotations.description }}*Description:* {{ .Annotations.description }}{{ end }}
  *Details:*
    {{ range $key, $value := .Labels }} • {{ $key }}: {{ $value }}
    {{ end }}
