version: '3.6'
services:

  promalert:
    container_name: test-promalert
    image: gcr.io/bugsnag-155907/promalert:1.2.13
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./config/promalert:/etc/promalert:ro
    environment:
      PROMALERT_BUGSNAG_RELEASE_STAGE: dev
      PROMALERT_HTTP_PORT: "8081"

  alertmanager:
    container_name: test-alertmanager
    image: prom/alertmanager:latest
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager:/config
    command: --config.file=/config/alertmanager.yml --log.level=debug

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/config/prometheus.yml'
    volumes:
      - ./config/prometheus:/etc/prometheus/config
    ports:
      - 9090:9090

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100