version: '3.7'

services:
  app:
    build:
      context: .

  ci:
    build:
      context: .
      target: ci

  test:
    build:
      context: .
      target: ci
    command: "go test ./... -race -timeout 30m -p 1"

  lint:
    build:
      context: .
      target: ci
    command: "golangci-lint run"